# -*- coding: utf-8 -*-
"""ChatbotMLops.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H_a-4qptEZpRCUuOqmky36PsYPQulAtK
"""

# If you need to install packages, run the following command in your terminal:
# pip install openai python-dotenv gradio

from dotenv import load_dotenv
load_dotenv(override=True)

import os
open_router_api_key = os.getenv("OPEN_ROUTER_API_KEY")

print(open_router_api_key)

"""# **Open Router LLM's**"""

from openai import OpenAI
import time

def open_router_call(model, task, message, history, source_lang=None, target_lang=None):
    open_router_ai = OpenAI(
        base_url="https://openrouter.ai/api/v1",
        api_key=open_router_api_key,
        timeout=30.0  # Timeout para evitar esperas infinitas
    )

    try:
        start_time = time.time()

        if task == "Translation":
            content = f"Translate the following text from {source_lang} to {target_lang}:"
        else:
            content = "Summarize the following text."  # Añadido punto final

        messages = [{"role": "system", "content": content}]

        # Construir historial de mensajes
        for msg in history:
            if isinstance(msg, list) and len(msg) == 2:
                # Formato Gradio: [mensaje_usuario, respuesta_asistente]
                messages.append({"role": "user", "content": msg[0]})
                messages.append({"role": "assistant", "content": msg[1]})
            elif isinstance(msg, dict):
                # Formato dict
                if msg["role"] == "user":
                    messages.append({"role": "user", "content": msg["content"]})
                elif msg["role"] == "assistant":
                    messages.append({"role": "assistant", "content": msg["content"]})

        messages.append({"role": "user", "content": message})

        print(f"Enviando petición a: {model}")

        completion = open_router_ai.chat.completions.create(
            model=model,
            messages=messages,
            max_tokens=800,  # Limitar para respuestas más rápidas
            temperature=0.7
        )

        elapsed_time = time.time() - start_time
        elapsed_ms = elapsed_time * 1000
        print(f"Respuesta recibida en {elapsed_time:.2f} segundos")

        return completion.choices[0].message.content, elapsed_ms

    except Exception as e:
        elapsed_time = time.time() - start_time
        elapsed_ms = elapsed_time * 1000
        print(f"Error: {e}")
        return f"Error: {str(e)}", elapsed_ms

languages = {
    "Spanish": "Spanish",
    "English": "English",
    "French": "French",
    "German": "German",
    "Italian": "Italian"
}

provider_models = {
    "Meta": [
        "meta-llama/llama-3.3-70b-instruct:free",
        "meta-llama/llama-4-maverick:free",
    ],
    "Google": [
        "google/gemma-3-27b-it:free",
        "google/gemini-2.0-flash-exp:free",
    ],
    "Qwen": [
        "qwen/qwen3-14b:free",
        "qwen/qwen-2.5-72b-instruct:free",
    ],
    "DeepSeek":[
        "deepseek/deepseek-r1-distill-llama-70b:free",
        "deepseek/deepseek-r1-0528-qwen3-8b:free"
    ]
}

import gradio as gr
import time

with gr.Blocks(title="Switchable LLM App con Gradio") as demo:
    gr.Markdown("# 🤖 Switchable LLM App\nSelect a provider, model, and task to process your message")

    chatbot = gr.Chatbot(
        label="Chat",
        height=400,
        show_copy_button=True
    )

    with gr.Row():
        provider = gr.Dropdown(
            list(provider_models.keys()),
            label="Provider",
            value="Meta",
        )
        model = gr.Dropdown(
            provider_models["Meta"],
            label="Model",
            value=provider_models["Meta"][0]
        )
        task = gr.Radio(
            ["Translation", "Summarize"],
            label="Task",
            value="Translation",
        )

    # Selectores de idioma para traducción
    with gr.Row(visible=True) as language_row:
        source_lang = gr.Dropdown(
            list(languages.keys()),
            label="Source Language",
            value="Spanish",
        )
        target_lang = gr.Dropdown(
            list(languages.keys()),
            label="Target Language",
            value="English",
        )

    with gr.Row():
        input_box = gr.Textbox(
            label="Input",
            placeholder="Type your message here...",
            lines=4
        )

    with gr.Row():
        submit = gr.Button("Submit", variant="primary")
        clear = gr.Button("Clear")


    status = gr.Textbox(label="Status", visible=False)
    inference_time = gr.Textbox(label="Inference time", visible=True)

    def update_models(provider):
        return gr.update(
            choices=provider_models[provider],
            value=provider_models[provider][0]
        )

    def toggle_language_inputs(task):

        return gr.update(visible=(task == "Translation"))

    def respond(message, history, provider_val, model_val, task_val, src_lang, tgt_lang):
        if not message or message.strip() == "":
            return history, "", "Please enter a message"


        temp_history = history + [[message, "Processing..."]]

        try:
            response, elapsed_ms = open_router_call(model_val, task_val, message, history, src_lang, tgt_lang)
            new_history = history + [[message, response]]
            time_str = f"{elapsed_ms:.1f} ms"
            return new_history, "", f"Response generated successfully", time_str

        except Exception as e:
            error_history = history + [[message, f"Error: {str(e)}"]]
            return error_history, "", f"Error occurred", "0.0 ms"

    provider.change(
        update_models,
        inputs=[provider],
        outputs=[model]
    )

    task.change(
        toggle_language_inputs,
        inputs=[task],
        outputs=[language_row]
    )

    submit.click(
        respond,
        inputs=[input_box, chatbot, provider, model, task, source_lang, target_lang],
        outputs=[chatbot, input_box, status, inference_time]
    )

    clear.click(
        lambda: ([], "", "Chat cleared"),
        outputs=[chatbot, input_box, status]
    )

demo.launch(share=False)