# -*- coding: utf-8 -*-
"""ChatbotMLops.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H_a-4qptEZpRCUuOqmky36PsYPQulAtK
"""

from dotenv import load_dotenv
load_dotenv(override=True)

import os
open_router_api_key = os.getenv("OPEN_ROUTER_API_KEY")

print(open_router_api_key)

"""# **Open Router LLM's**"""

from openai import OpenAI
import time

def open_router_call(model, task, message, history):
    open_router_ai = OpenAI(
        base_url="https://openrouter.ai/api/v1",
        api_key=open_router_api_key,
        timeout=30.0
    )

    try:
        start_time = time.time()

        if task == "Translation":
            content = "Translate the following text from Spanish to English:"
        else:
            content = "Summarize the following text:"

        messages = [{"role": "system", "content": content}]


        for msg in history:
            if isinstance(msg, list) and len(msg) == 2:

                messages.append({"role": "user", "content": msg[0]})
                messages.append({"role": "assistant", "content": msg[1]})
            elif isinstance(msg, dict):

                if msg["role"] == "user":
                    messages.append({"role": "user", "content": msg["content"]})
                elif msg["role"] == "assistant":
                    messages.append({"role": "assistant", "content": msg["content"]})

        messages.append({"role": "user", "content": message})

        print(f"Enviando petición a: {model}")

        completion = open_router_ai.chat.completions.create(
            model=model,
            messages=messages,
            max_tokens=500,
            temperature=0.7
        )

        elapsed_time = time.time() - start_time
        print(f"Respuesta recibida en {elapsed_time:.2f} segundos")

        return completion.choices[0].message.content

    except Exception as e:
        print(f"Error: {e}")
        return f"Error: {str(e)}"

provider_models = {
    "Meta (Rápido)": [
        "meta-llama/llama-3.3-70b-instruct:free",
        "meta-llama/llama-4-maverick:free",
    ],
    "Google": [
        "google/gemma-3-27b-it:free",
        "google/gemini-2.0-flash-exp:free",
    ],
    "Microsoft": [
        "microsoft/mai-ds-r1:free",
    ],
    "Qwen": [
        "qwen/qwen3-14b:free",
        "qwen/qwen-2.5-72b-instruct:free",
    ],
    "Mistral": [
        "mistralai/mistral-7b-instruct:free",
        "mistralai/mistral-small-24b-instruct-2501:free"
    ],
    "DeepSeek":[
        "deepseek/deepseek-r1-distill-llama-70b:free",
        "deepseek/deepseek-r1-0528-qwen3-8b:free"
    ]
}

import gradio as gr
import time

with gr.Blocks(title="Switchable LLM App con Gradio") as demo:
    gr.Markdown("# 🤖 Switchable LLM App\nSelect a provider, model, and task to process your message")

    chatbot = gr.Chatbot(
        label="Chat",
        height=400,
        show_copy_button=True
    )

    with gr.Row():
        provider = gr.Dropdown(
            list(provider_models.keys()),
            label="Provider",
            value="Meta (Rápido)",
        )
        model = gr.Dropdown(
            provider_models["Meta (Rápido)"],
            label="Model",
            value=provider_models["Meta (Rápido)"][0]
        )
        task = gr.Radio(
            ["Translation", "Summarize"],
            label="Task",
            value="Translation",
        )

    with gr.Row():
        input_box = gr.Textbox(
            label="Input",
            placeholder="Type your message here...",
            lines=5
        )

    with gr.Row():
        submit = gr.Button("Submit", variant="primary")
        clear = gr.Button("Clear")

    status = gr.Textbox(label="Status", visible=False)

    def update_models(provider):
        return gr.update(
            choices=provider_models[provider],
            value=provider_models[provider][0]
        )

    def respond(message, history, provider_val, model_val, task_val):
        if not message or message.strip() == "":
            return history, "", "Please enter a message"

        temp_history = history + [[message, "Processing..."]]

        try:
            response = open_router_call(model_val, task_val, message, history)
            new_history = history + [[message, response]]
            return new_history, "", f"Response generated successfully"

        except Exception as e:
            error_history = history + [[message, f"Error: {str(e)}"]]
            return error_history, "", f"Error occurred"

    provider.change(
        update_models,
        inputs=[provider],
        outputs=[model]
    )

    submit.click(
        respond,
        inputs=[input_box, chatbot, provider, model, task],
        outputs=[chatbot, input_box, status]
    )

    clear.click(
        lambda: ([], "", "Chat cleared"),
        outputs=[chatbot, input_box, status]
    )

demo.launch(share=False)